### ISSUE TITLE
[Suggestion] Change `noExternal` to `external`

### ISSUE THREAD

**Issue by finscn** [pixijs/pixify#13]
Change `noExternal` to `external` , 
then change the default value from `false` to `true` ,
and change all  `!args.noExternal` to  `args.external`.

'negation-parameter' is not good , I think.

**Comment by bigtimebuddy** [comment]
Sounds good. Could you make a PR?

**Comment by finscn** [comment]
OK. I will

**Comment by finscn** [comment]
Done after commit  ef48a19 .
