### ISSUE TITLE
Save to use pixify for other libraries?

### ISSUE THREAD

**Issue by dcodeIO** [pixijs/pixify#5]
Currently running this in development for protobuf.js as it nicely abstracts the build process away for me. Is it safe to rely on this, i.e. that it remains general enough for other libraries as well?

**Comment by bigtimebuddy** [comment]
Sure, go for it! 

There's nothing in this module that is specific to Pixi.js or any of it's related libraries. It's a convenience to provide solutions to some of the annoying Browserify stuff: watching, sourcemaps, preprocessing, minified vs unminified versions etc. We are particularly interested in using with npm scripts (and not gulp, grunt or some other task runner). 

Feel free to use it and welcome any feature requests.

**Comment by dcodeIO** [comment]
Great! First feature request would be to be able to supply an alternative path to the license file :). When I find the time I can also send a PR for this if you'd prefer one.

**Comment by bigtimebuddy** [comment]
Definitely! PRs welcome.

**Comment by bigtimebuddy** [comment]
Going to close this issue.
